keys:
  - &jerrita age1feqjynjlfu3tx7xukcrqjxfg7gyke0sy9c9gskrhp5laxy9md3ss56s482
  - &astral age1862lkkgtfnm24l0q3umxllrtdfvlgj59cwp5xnjjehw6wjan0cnsrermu8
  - &rana age1xwltygtx2gl6kl3j3z9vqzj8d5t0wexcr8qehg8pwazfw7rfqfps687tk5
creation_rules:
  - path_regex: secrets/common/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *jerrita
      - *astral
      - *rana
  - path_regex: secrets/astral.yaml
    key_groups:
    - age:
      - *jerrita
      - *astral
